CREATE TABLE species (
  species_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  species_name VARCHAR(255) NOT NULL UNIQUE,
  genus_id INTEGER NOT NULL,
  CONSTRAINT fk_genus FOREIGN KEY (genus_id) REFERENCES genera (genus_id)
);


INSERT INTO species (species_name, genus_id) VALUES
  ('chaus chaus', (SELECT genus_id FROM genera WHERE genus_name = 'Felis')),
  ('chaus affinis', (SELECT genus_id FROM genera WHERE genus_name = 'Felis')),
  ('chaus furax', (SELECT genus_id FROM genera WHERE genus_name = 'Felis')),
  ('chaus kelaarti', (SELECT genus_id FROM genera WHERE genus_name = 'Felis')),
  ('chaus kutas', (SELECT genus_id FROM genera WHERE genus_name = 'Felis')),
  ('chaus maimanah', (SELECT genus_id FROM genera WHERE genus_name = 'Felis')),
  ('chaus nilotica', (SELECT genus_id FROM genera WHERE genus_name = 'Felis')),
  ('chaus oxiana', (SELECT genus_id FROM genera WHERE genus_name = 'Felis')),
  ('chaus prateri', (SELECT genus_id FROM genera WHERE genus_name = 'Felis')),
  ('lybica', (SELECT genus_id FROM genera WHERE genus_name = 'Felis')),
  ('margarita', (SELECT genus_id FROM genera WHERE genus_name = 'Felis')),
  ('nigripes', (SELECT genus_id FROM genera WHERE genus_name = 'Felis')),
  ('silvestris catus', (SELECT genus_id FROM genera WHERE genus_name = 'Felis')),
  ('silvestris caucasica', (SELECT genus_id FROM genera WHERE genus_name = 'Felis')),
  ('silvestris caudata', (SELECT genus_id FROM genera WHERE genus_name = 'Felis')),
  ('silvestris chutuchta', (SELECT genus_id FROM genera WHERE genus_name = 'Felis')),
  ('silvestris foxi', (SELECT genus_id FROM genera WHERE genus_name = 'Felis')),
  ('silvestris griselda', (SELECT genus_id FROM genera WHERE genus_name = 'Felis')),
  ('silvestris haussa', (SELECT genus_id FROM genera WHERE genus_name = 'Felis')),
  ('silvestris iraki', (SELECT genus_id FROM genera WHERE genus_name = 'Felis')),
  ('silvestris jordansi', (SELECT genus_id FROM genera WHERE genus_name = 'Felis')),
  ('silvestris mellandi', (SELECT genus_id FROM genera WHERE genus_name = 'Felis')),
  ('silvestris rubida', (SELECT genus_id FROM genera WHERE genus_name = 'Felis')),
  ('silvestris tristami', (SELECT genus_id FROM genera WHERE genus_name = 'Felis')),
  ('silvestris ugandae', (SELECT genus_id FROM genera WHERE genus_name = 'Felis')),
  
  ('forsteri', (SELECT genus_id FROM genera WHERE genus_name = 'Aptenodytes')),

  ('lagopus', (SELECT genus_id FROM genera WHERE genus_name = 'Vulpes')),

  ('nubicola', (SELECT genus_id FROM genera WHERE genus_name = 'Cophixalus')),
  ('aenigma', (SELECT genus_id FROM genera WHERE genus_name = 'Cophixalus')),

  ('callidryas', (SELECT genus_id FROM genera WHERE genus_name = 'Agalychnis')),

  ('maritimus maritimus', (SELECT genus_id FROM genera WHERE genus_name = 'Ursus'));
