CREATE TABLE genera (
  genus_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  genus_name VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO genera (genus_name) VALUES
  ('Cophixalus'), -- Género de ranas
  ('Agalychnis'), -- Género de ranas
  ('Felis'),       -- Género de felinos
  ('Vulpes'),     -- Género del zorro ártico
  ('Ursus'),      -- Género del oso polar
  ('Aptenodytes');   --Género del pinguino emperador
  
