CREATE TABLE institutions (
  institution_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institution_name VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO institutions (institution_name) VALUES 
  ('Smithsonian Institution'),
  ('British Library'),
  ('Harvard University Library'),
  ('University of Cambridge'),
  ('Princeton University'),
  ('Kings College London'),
  ('University of Vienna'),
  ('University of Göttingen'),
  ('KTH Royal Institute of Technology'),
  ('Niels Bohr Institute'),
  ('California Institute of Technology'),
  ('Cornell University'),
  ('University of Massachusetts Amherst');