CREATE TABLE collections (
  collection_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_name VARCHAR(255) NOT NULL UNIQUE,
  description VARCHAR(1023)
);

INSERT INTO collections (collection_name, description)
VALUES
  ('Jungle', 'A collection of research articles exploring the biodiversity and ecological dynamics of tropical rainforests.'),
  ('Desert', 'A collection of studies focused on the adaptation of species and ecosystems to arid and desert environments.'),
  ('Tundra', 'A collection of research focused on the flora, fauna, and climate of Arctic & alpine tundra ecosystems.'),
  ('Domestic', 'A collection of research focused on domestic animals, their development and impact on the ecosystem.')
  ;
