CREATE TABLE authors (
  author_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  personal_id VARCHAR(255) NOT NULL UNIQUE,
  first_name VARCHAR(255) NOT NULL,
  middle_name VARCHAR(255),
  last_name_1 VARCHAR(255) NOT NULL,
  last_name_2 VARCHAR(255),
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(35),
  address INTEGER,
  CONSTRAINT fk_address FOREIGN KEY (address) REFERENCES addresses (address_id)
);

INSERT INTO authors (personal_id, first_name, last_name_1, last_name_2, email, phone, address) VALUES
  ('012345678', 'Blizzard', 'Entertainment', NULL, 'contact@blizzard.com', '123-456-7890', (SELECT address_id FROM addresses WHERE address = '123 Main St.')),
  ('123456789', 'John', 'Doe', 'Jr.', 'john.doe@gmail.com', '123-456-7890', NULL);


INSERT INTO authors (personal_id, first_name, middle_name, last_name_1, last_name_2, email, phone, address) 
VALUES ('987654321', 'Jane', 'M.', 'Goodall', NULL, 'jgoodall@janegoodall.org', '202-378-2000', (SELECT address_id FROM addresses WHERE address = '456 Elm St')),
 ('111111111', 'Charles', 'R.', 'Darwin', NULL, 'cdarwin@downhouse.org.uk', '01233-123456', (SELECT address_id FROM addresses WHERE address = '456 Elm St')), 
 ('222222222', 'Rosalind', 'E.', 'Franklin', NULL, 'rfranklin@kings.ac.uk', '020-123-4567', NULL),
 ('333333333', 'E.O.', 'W.', 'Wilson', NULL, 'ewilson@harvard.edu', '617-495-1000', (SELECT address_id FROM addresses WHERE address = '456 Elm St')),
 ('444444444', 'James', 'D.', 'Watson', NULL, 'jwatson@cshl.edu', '516-367-8455', (SELECT address_id FROM addresses WHERE address = '456 Elm St')),
 ('555555555', 'Francis', 'H.', 'Crick', NULL, 'fcrick@salk.edu', '858-123-4567', (SELECT address_id FROM addresses WHERE address = '456 Elm St')),
 ('666666666', 'Barbara', 'M.', 'McClintock', NULL, 'bmcclintock@cornell.edu', '607-255-5400', (SELECT address_id FROM addresses WHERE address = '456 Elm St')), 
 ('777777777', 'Theodosius', 'D.', 'Dobzhansky', NULL, 'tdobzhansky@rockefeller.edu', '212-327-8000', (SELECT address_id FROM addresses WHERE address = '456 Elm St')), 
 ('888888888', 'Lynn', 'M.', 'Margulis', NULL, 'lmargulis@umass.edu', '413-545-2222', (SELECT address_id FROM addresses WHERE address = '456 Elm St')), 
 ('999999999', 'Seymour', 'S.', 'Benzer', NULL, 'sbenzer@caltech.edu', '626-395-6001', (SELECT address_id FROM addresses WHERE address = '456 Elm St'));