CREATE TABLE addresses (
  address_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  address VARCHAR(255) NOT NULL,
  city VARCHAR(255) NOT NULL,
  state VARCHAR(255) NOT NULL,
  country INTEGER NOT NULL,
  zip VARCHAR(50) NOT NULL,
  CONSTRAINT fk_country FOREIGN KEY (country) REFERENCES countries (country_id)
);

INSERT INTO addresses (address, city, state, country, zip) VALUES
  ('123 Main St.', 'Anytown', 'CA', (SELECT country_id FROM countries WHERE country_name = 'United States'), '12345'),
  ('456 Elm St.', 'Anytown', 'CA', (SELECT country_id FROM countries WHERE country_name = 'United States'), '12345'),
  ('789 Oak St.', 'Anytown', 'CA', (SELECT country_id FROM countries WHERE country_name = 'United States'), '12345');
